### ISSUE TITLE
Guard Dogs/Wolves should have a small random chance to trip (knockdown)

### ISSUE THREAD

**Issue by SeanMJOBrien** [b5635/the-frozen-north#343]
It's very powerful, so should be rarely employed. 1:25 for first attack only? I'm just spitballing.

**Comment by b5635** [comment]
Hmm, I do feel like it could be annoying to players. They're a bit common in certain parts of the module, but I'll think about it. There's a few monsters that I believe employ knockdown, such as high level fighters and dire wolves.

**Comment by SeanMJOBrien** [comment]
Could just give it a low DC to start, and adjust the DC and frequency as needed? Would really mess up a Mage's day... I only say powerful because it takes you out for a round, and as a new character (you see dogs in the earlier quests) that's a big deficit in the "action economy".

**Comment by b5635** [comment]
I think I would prefer leveraging the knockdown feat. I'll think about adding it :) I just realized that it might be okay for canine enemies in general, because even though they appear early on, their AB isn't that high so knockdown attacks may have a low chance of succeeding. I also think it would be good if it was rare, as you have stated. I'll have to look into the AI to see if it is possible.

**Comment by b5635** [comment]
Based on Discord discussion, it seems the consensus is to abstain from the feature. I will keep it in mind for some enemies, though!
