### ISSUE TITLE
Valuable item webhook variable should be cleared over time

### ISSUE THREAD

**Issue by Logg-y** [b5635/the-frozen-north#484]
What if you buy a valuable item from a store that was sold by another player?

**Comment by b5635** [comment]
I think the fix here would be to clear the variable when it is sold to a merchant.

There's an interesting use-case of it being traded between players and it not triggering, but I think this should be okay - no webhook should trigger when traded between players through dropping an item, bartering, etc. Otherwise, they can spam notifications by swapping a lot of items
