### ISSUE TITLE
Walking on roads and in towns should be faster

### ISSUE THREAD

**Issue by b5635** [b5635/the-frozen-north#699]
Daz made a script for this

**Comment by Logg-y** [comment]
Side note: "dirt" roads can't really be detected with this, because they simply use the dirt surface material. Even in grassy areas there is some of this that clearly isn't a road, such as fields where crops grow.

Stone is also used for the "rocks" in areas, some of which are walkable. This might turn out to be too unwieldy to implement for your average wilderness area.

**Comment by b5635** [comment]
we probably need to check by tile resref as well, perhaps that might be enough

**Comment by b5635** [comment]
https://github.com/Daztek/EquinoxFramework/blob/main/Systems/ef_s_travel.nss
